<a href="https://colab.research.google.com/github/Dorisgom/proyectos/blob/main/Librerias_Python_clase26052025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Analisis de datos**
El proceso que se encarga interpretar, manipular, recolectar, clasificar, analizar, recopilar, limpiar o depurar toda informacion para una toma desicion, que permita ayudar a las organizaciones.

## **Librerias de Python**
**-Numpy:** Es una libreria que me permite hacer operaciones matematicas (arreglos, estadistica, algebra, arimetica , entre otras)
**Pandas:** Es una libreria que me permite manipular y hacer operaciones como: Limpieza datos, leer datos, analisis explotorio , analisis descriptivo, ETL(Extraccion, Transformacion, y Carga).
**Matplolib:** Es una libreria que me permite, realizar analisis estadistico como lo son: Histogramas, Diagrama de pastel, diagrama lineas, dispersion entre otras.
**Seaborn:** Es una libreria que me permite, realizar analisis estadisticos
avanzados .

**Introduccion a Numpy**

En un Numpy existen estructuras de datos llamadas arreglos , donde son aquellos que tienen 1 un indice y tiene varias dimensiones entre esas son:

Arreglo Unidimensional: Tiene una dimension

Arreglo Bidimensional: Tiene 2 dimensiones

Arreglo Tridimensional: Tiene 3 dimensiones

In [ ]:
# Importamos la libreria de numpy
import numpy as np

# Dimensionamos el arreglo 1 dimension
vector = np.array([1,4,5,7,8,9,4,3,8,9,4])
print(vector)

# Imprimir la longitud del arreglo
print(len(vector))

#Indexacion del vector
print(vector[3])

#Actualizar el valor del vector o arreglo unidimensional
vector[3] =50
print(vector)

# Slicing es recorrer el indice del arreglo [indice_inicial: indice_final-1:paso]
print(vector[0:10])
print(vector[0:10:2])

# Ciclos
for valor in vector:
  print(valor)





[1 4 5 7 8 9 4 3 8 9 4]
11
7
[ 1  4  5 50  8  9  4  3  8  9  4]
[ 1  4  5 50  8  9  4  3  8  9]
[1 5 8 4 8]
1
4
5
50
8
9
4
3
8
9
4


In [ ]:
#Atributos

# Atributos del arreglo
print('Tipo de Arreglo',vector.dtype)
print('Tamano del arreglo', vector.size)
print('Dimensiones del arreglo',vector.ndim)
print('Elemento de cada dimension', vector.shape)



Tipo de Arreglo int64
Tamano del arreglo 11
Dimensiones del arreglo 1
Elemento de cada dimension (11,)


In [ ]:
#Metodos

# Definimos la lista
lista = [1,2,3,4,5]
vector= np.array(lista)

print(vector, type(vector))

# Multiplicacion entre arreglos
arreglouno = np.array([2,4,6,8])
arreglodos = np.array([3,5,7,9])
print(arreglouno*arreglodos)



[1 2 3 4 5] <class 'numpy.ndarray'>
[ 6 20 42 72]


In [ ]:
# Metodos estadisticos
print("Suma es: ", vector.sum())
print("Promedio es:", vector.mean())
print("Valor maximo: ", vector.max())
print("Valor minimo: ", vector.min())


Suma es:  15
Promedio es: 3.0
Valor maximo:  5
Valor minimo:  1


In [ ]:
# Arreglos de 2 dimensiones
matriz = np.array(([1,2,5,4],[9,5,5,7],[6,0,0,8],[3,9,6,5]))
print(matriz)

# Cantidad de elementos de la matriz
print(len(matriz))

# Indexacion de la matriz
print(matriz[2,2])

# Actualizar un valor en la matriz
matriz[2,2] =7

print(matriz)


[[1 2 5 4]
 [9 5 5 7]
 [6 0 0 8]
 [3 9 6 5]]
4
0
[[1 2 5 4]
 [9 5 5 7]
 [6 0 7 8]
 [3 9 6 5]]


In [ ]:
# Atributos de arreglos 2D
print('Tipo de matriz: ', matriz.dtype)
print('Tamano de la matriz', matriz.size)
print('Dimensiones del arreglo', matriz.ndim)
print('Elementos de cada dimension de la matriz: ', matriz.shape)

Tipo de matriz:  int64
Tamano de la matriz 16
Dimensiones del arreglo 2
Elementos de cada dimension de la matriz:  (4, 4)


In [ ]:
# Metodo de np.array() - crear una a partir de una seucencia de datos
lista= [[1,2,5,4],[9,5,5,7], [6,0,0,8],[3,9,6,5]]
matriz =(np.array(lista))
print(matriz, type(matriz))

# Metodos estadisticos
print('Suma es: ',matriz.sum())
print('Promedio es: ', matriz.mean())
print('Valor maximo', matriz.max())
print("Valor minimo", matriz.min())

#  Metodos propios 2D
# Cambiar la forma de la matriz de 4x4 a 2x8
matriz_reshape=matriz.reshape(2,8)
print(" \nMatriz con forma cambiada:")
print(matriz_reshape)

# Transponer matriz
print("\nMatriz transpuesta:")
matriz_transpose= matriz_reshape.transpose()
print(matriz_transpose)

[[1 2 5 4]
 [9 5 5 7]
 [6 0 0 8]
 [3 9 6 5]] <class 'numpy.ndarray'>
Suma es:  75
Promedio es:  4.6875
Valor maximo 9
Valor minimo 0
 
Matriz con forma cambiada:
[[1 2 5 4 9 5 5 7]
 [6 0 0 8 3 9 6 5]]

Matriz transpuesta:
[[1 6]
 [2 0]
 [5 0]
 [4 8]
 [9 3]
 [5 9]
 [5 6]
 [7 5]]


In [ ]:
vectorUno =np.array([1,2,3])
vectorDos= np.array([4,5,6])

#Suma de vectores
suma=vectorUno+vectorDos
print(suma, "\n")

sumaDos=vectorUno+6
print(sumaDos,"\n")

# Producto punto
producto= np.dot(vectorUno, vectorDos)
print(producto,"\n")

[5 7 9] 

[7 8 9] 

32 



In [ ]:
import pandas as pd


# Crear DataFrame
datos = pd.DataFrame({
    'Nombre':['Juan', 'Ana', 'Pedro', 'Lucia'],
    'Edad':[25,30,28,22],
    'Ciudad': ['Bogota','Medellin', 'Cali','Barrranquilla'],
    'Profesion':['Sistemas', 'Medicina', 'Medicina', 'Sistemas']
})

# Analisis exploratorio (EDA): Es aquel que permite conocer la estructura de los datos o dataframe como: tamano, columnas, tipos de datos,
# Valores, Si hay registros vacios etcc......

# Imprimir la forma del dataframe
print(datos.shape)

# Imprimir las etiquetas de indice
print(datos.index)

# Imprimir las etiquetas de columnas
print(datos.columns)

# Imprimir los tipos de datos de las columnas
print(datos.dtypes)

#Imprimir los valores del DataFrame
print(datos.values)

# Imprimir si el dataframe esta vacio
print(datos.empty)

# Imprimir el numero total de elementos en el DataFrame
print(datos.size)

# Imprimir la cantidad de dimensiones del DataFrame
print(datos.ndim)



(4, 4)
RangeIndex(start=0, stop=4, step=1)
Index(['Nombre', 'Edad', 'Ciudad', 'Profesion'], dtype='object')
Nombre       object
Edad          int64
Ciudad       object
Profesion    object
dtype: object
[['Juan' 25 'Bogota' 'Sistemas']
 ['Ana' 30 'Medellin' 'Medicina']
 ['Pedro' 28 'Cali' 'Medicina']
 ['Lucia' 22 'Barrranquilla' 'Sistemas']]
False
16
2


# **Importaciones de datos**
Son las fuentes de donde recopilamos nuestros datos con su respectivo tipo de archivo. Entre esas tenemos:

- CSV: La abreviatura "CSV" significa "valores separados por comas" (del inglés ‘comma separated value’) y describe la estructura de un archivo de texto con el que se intercambian y almacenan datos estructurados de forma sencilla.
- Excel:Es un programa que permite editar hojas de cálculo desarrollada por Microsoft para Windows, macOS, Android y iOS.
Cuenta con cálculos, gráficas, tablas calculares.
- SQL:siglas en inglés significa Lenguaje de Consulta Estructurada (Structured Query Language), es un lenguaje de programación diseñado para actualizar, obtener, y calcular información en bases de datos relacionales.
- JSON: es un formato de texto sencillo para el intercambio de datos. Se trata de un subconjunto de la notación literal de objetos de JavaScript, y que se conforma por clave y valor.
- API REST:Es una arquitectura para intercambiar datos entre aplicaciones.




In [ ]:
# Cargar archivos CSV
datasetPlano = pd.read_csv('/content/CalificacionesTXT.csv', sep=',')

# Muestra toda la data
datasetPlano

# Muestra los primeros 5 registros del dataset
datasetPlano.head()

# Muestras los ultimos 5 registros del dataset
datasetPlano.tail()

# Muestra informacion tecnica de las columnas del dataset
datasetPlano.info()

# Muestra informacion estadisitica del dataset
datasetPlano.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   ITEM         20 non-null     int64 
 1   NOMBRES      20 non-null     object
 2   APELLIDOS    20 non-null     object
 3   Programa     20 non-null     object
 4   Genero       20 non-null     object
 5   Matematicas  18 non-null     object
 6   Español      20 non-null     object
 7   Ciencias     19 non-null     object
 8   Idiomas      18 non-null     object
dtypes: int64(1), object(8)
memory usage: 1.5+ KB


ITEM
count  20.00000
mean   10.50000
std     5.91608
min     1.00000
25%     5.75000
50%    10.50000
75%    15.25000
max    20.00000

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')



Mounted at /content/drive/


In [ ]:
import pandas as pd

#Cargar datos desde excel
datasetExcel = pd.read_excel('/content/drive/MyDrive/ArchivosColab/Calificaciones.xlsx')
datasetExcel

# Muestra los primeros 5 registros del dataset
datasetExcel.head()

# Muestras los ultimos 5 registros del dataset
datasetExcel.tail()

# Muestra informacion tecnica de las columnas del dataset
datasetExcel.info()

# Muestra informacion estadisitica del dataset
datasetExcel.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   ITEM         20 non-null     int64  
 1   NOMBRES      20 non-null     object 
 2   APELLIDOS    20 non-null     object 
 3   Programa     20 non-null     object 
 4   Genero       20 non-null     object 
 5   Matematicas  18 non-null     float64
 6   Español      20 non-null     float64
 7   Ciencias     19 non-null     float64
 8   Idiomas      18 non-null     float64
dtypes: float64(4), int64(1), object(4)
memory usage: 1.5+ KB


ITEM  Matematicas    Español   Ciencias    Idiomas
count  20.00000     18.00000  20.000000  19.000000  18.000000
mean   10.50000      3.18500   2.919500   2.978947   2.764444
std     5.91608      0.88603   0.943825   0.870229   0.638650
min     1.00000      1.66000   1.680000   1.840000   1.690000
25%     5.75000      2.55000   2.120000   2.260000   2.292500
50%    10.50000      3.24000   2.850000   2.670000   2.760000
75%    15.25000      4.05750   3.667500   3.700000   3.222500
max    20.00000      4.20000   5.000000   4.310000   4.000000

In [ ]:
#Cargar datos desde github
url = 'https://github.com/carlosgomez0717/Machine-Learning/raw/main/Calificaciones.xlsx'

datasetExcelURL = pd.read_excel(url, sheet_name='Hoja1')

datasetExcelURL

# Muestra los primeros 5 registros del dataset
datasetExcelURL.head()

# Muestras los ultimos 5 registros del dataset
datasetExcelURL.tail()

# Muestra informacion tecnica de las columnas del dataset
datasetExcelURL.info()

# Muestra informacion estadisitica del dataset
datasetExcelURL.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   ITEM         20 non-null     int64  
 1   NOMBRES      20 non-null     object 
 2   APELLIDOS    20 non-null     object 
 3   Programa     20 non-null     object 
 4   Genero       20 non-null     object 
 5   Matematicas  18 non-null     float64
 6   Español      20 non-null     float64
 7   Ciencias     19 non-null     float64
 8   Idiomas      18 non-null     float64
dtypes: float64(4), int64(1), object(4)
memory usage: 1.5+ KB


ITEM  Matematicas    Español   Ciencias    Idiomas
count  20.00000     18.00000  20.000000  19.000000  18.000000
mean   10.50000      3.18500   2.919500   2.978947   2.764444
std     5.91608      0.88603   0.943825   0.870229   0.638650
min     1.00000      1.66000   1.680000   1.840000   1.690000
25%     5.75000      2.55000   2.120000   2.260000   2.292500
50%    10.50000      3.24000   2.850000   2.670000   2.760000
75%    15.25000      4.05750   3.667500   3.700000   3.222500
max    20.00000      4.20000   5.000000   4.310000   4.000000